### ISSUE TITLE
Argonia Cup Environment

### ISSUE THREAD

**Issue by fallscameron01** [MissouriMRR/Simulation-2023#3]
# Argonia Cup Environment

## Problem

Create an environment for testing air drop related code as described in Argonia Cup 2023 rules.

## Solution

Create an environment for testing Argonia Cup related code.

## Additional Resources

Argonia Cup 2023 Rules: [http://www.argoniacup.com/wp-content/uploads/2022/07/2023-Argonia-Cup-Rules.pdf](http://www.argoniacup.com/wp-content/uploads/2022/07/2023-Argonia-Cup-Rules.pdf)

**Comment by cjhr95** [comment]
Argonia Cup 2024 does not require a drone for the completion of the deliverables.
